# Generated by Django 5.2 on 2025-04-02 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Savings', 'Savings'), ('Investment', 'Investment'), ('Gifts', 'Gifts'), ('Fitness', 'Fitness'), ('Pet', 'Pet'), ('Home', 'Home'), ('Personal Care', 'Personal Care'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('Account', 'Account'), ('Card', 'Card')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
