# Generated by Django 5.1.8 on 2025-04-10 04:00

import budget.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_handle_category_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[budget.validators.validate_positive_amount, budget.validators.validate_budget_limit, budget.validators.validate_currency_format]),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[budget.validators.validate_positive_amount, budget.validators.validate_currency_format]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(validators=[budget.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[budget.validators.validate_positive_amount, budget.validators.validate_currency_format]),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(validators=[budget.validators.validate_future_date]),
        ),
    ]
